<?php

/**
 * @file
 * Contains bt_media.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bt_media_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bt_media module.
    case 'help.page.bt_media':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Btester Multimedia') . '</p>';

      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bt_media_theme() {
  return [
    'bt_media' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_local_tasks_alter().
 */
function bt_media_local_tasks_alter(&$local_tasks) {
  $local_tasks['entity.media.collection']['base_route'] = 'bt_cms.website';
}


/**
 * Implements hook_menu_local_actions_alter().
 */
function bt_media_menu_local_actions_alter(&$local_actions) {
  $local_actions['media.add']['appears_on'][0] = 'entity.media.collection';
  $local_actions['media.add']['title'] = t('Add media');
}

/**
 * Implements hook_entity_type_alter().
 */
function bt_media_entity_type_alter(array &$entity_types) {
  $entity_types['media_type']->setHandlerClass('access', 'Drupal\bt_media\MediaTypeAccessControlHandler');
}
