<?php

/**
 * @file
 * Contains bt_media.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bt_media_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bt_media module.
    case 'help.page.bt_media':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Btester Multimedia') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bt_media_theme() {
  return [
    'bt_media' => [
      'render element' => 'children',
    ],
  ];
}


/**
 * Implements hook_menu_local_actions_alter().
 */
function bt_media_menu_local_actions_alter(&$local_actions) {
    $local_actions['media.add']['appears_on'][0] = 'page_manager.page_view_app_website_media_app_website_media-panels_variant-0';
    $local_actions['media.add']['appears_on'][1] = 'page_manager.page_view_app_website_media_app_website_media-panels_variant-1';
    $local_actions['media.add']['title'] = t('Add multimedia element');
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
/*function bt_media_menu_local_tasks_alter(&$data, $route_name) {
    $current_user = \Drupal::service('current_user');
    $user_id = $current_user->id();
    $user_account = User::load($user_id);

    $routes = [
        'page_manager.page_view_app_app-panels_variant-0',
        'bt_page_drag_and_drop',
        'page_manager.page_view_app_website_app_website-panels_variant-0',
        'page_manager.page_view_app_website_content_app_website_content-panels_variant-0',
        'page_manager.page_view_app_website_content_app_website_content-panels_variant-1',
        'page_manager.page_view_app_website_comments_app_website_comments-panels_variant-0',
        'page_manager.page_view_app_website_blocks_app_webiste_blocks-panels_variant-0',
        'page_manager.page_view_app_website_media_app_website_media-panels_variant-0',
        'page_manager.page_view_app_website_media_app_website_media-panels_variant-1',
        'page_manager.page_view_app_website_polls_app_website_polls-panels_variant-0',
        'page_manager.page_view_app_website_forums_app_website_forums-panels_variant-0',
        'page_manager.page_view_app_website_faq_app_website_faq-panels_variant-0',
    ];

    if (in_array($route_name, $routes)) {
        if (PersonaUtility::hasPersona($user_account, 'bt_content_editor_publisher')){
            unset($data['tabs'][0]['bt_website_content_writer_task']);
            unset($data['tabs'][1]['bt_website_content_writer_default_task']);
            unset($data['tabs'][0]['bt_website_documents_writer_task']);
            unset($data['tabs'][0]['bt_website_media_writer_task']);
        }elseif(PersonaUtility::hasPersona($user_account, 'bt_content_creator')){
            unset($data['tabs'][0]['bt_website_content_admin_task']);
            unset($data['tabs'][1]['bt_website_content_admin_default_task']);
            unset($data['tabs'][0]['bt_website_documents_admin_task']);
            unset($data['tabs'][0]['bt_website_media_admin_task']);
        }
    }
}*/

/**
 * Implements hook_entity_type_alter().
 */
function bt_media_entity_type_alter(array &$entity_types) {
    $entity_types['media_bundle']->setHandlerClass('access', 'Drupal\bt_media\MediaTypeAccessControlHandler');
}