# @see https://github.com/drevops/drupal_circleci
version: 2
aliases:
  # SSH deployment key fingerprint from CircleCI App -> Project -> Settings -> SSH Permissions.
  # Replace the value for your project.
  - &deploy_ssh_fingerprint "d1:d2:3b:87:e8:6c:c1:7c:d2:d7:65:43:30:7b:e6:6b"
  - &container_config
    working_directory: ~/project
    docker:
      - image: cimg/php:8.1-browsers

job-build: &job-build
  steps:
    - checkout
    - run: .circleci/build.sh
    - run: .circleci/lint.sh
    - run: .circleci/test.sh
    - run:
        command: .circleci/process-artifacts.sh
        when: always
    - store_test_results:
        path: /tmp/test_results
    - store_artifacts:
        path: /tmp/artifacts

jobs:
  build-php-8.0:
    <<: *container_config
    docker:
      - image: cimg/php:8.0-browsers
    <<: *job-build

  build-php-8.1:
    <<: *container_config
    docker:
      - image: cimg/php:8.1-browsers
    <<: *job-build

  build-php-8.0-legacy:
    <<: *container_config
    docker:
      - image: cimg/php:8.0-browsers
    environment:
      DRUPAL_VERSION: 9.3.22
      DRUPAL_PROJECT_SHA: 9.x
    <<: *job-build

  build-php-8.1-legacy:
    <<: *container_config
    docker:
      - image: cimg/php:8.1-browsers
    environment:
      DRUPAL_VERSION: 9.4.15
      DRUPAL_PROJECT_SHA: 9.4.15
    <<: *job-build

  build-php-8.1-next:
    <<: *container_config
    docker:
      - image: cimg/php:8.1-browsers
    environment:
      DRUPAL_VERSION: 10@beta2
      DRUPAL_PROJECT_SHA: 10.x
    <<: *job-build

  deploy:
    <<: *container_config
    environment:
      DEPLOY_SSH_FINGERPRINT: *deploy_ssh_fingerprint
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - *deploy_ssh_fingerprint
      - run: DEPLOY_BRANCH=${CIRCLE_BRANCH} .circleci/deploy.sh

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              # 1.0.x, 2.3.x, 9.x, 10.x, 9.x-2.x, ci, ci-test
              only: /^[0-9]+.[0-9]+.x$|^[0-9]+.x(?:\-[0-9]+\.x)?$|^ci/
